name: Label PRs based on files changed
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v3.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"