name: "Publish Docker Image"

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  build-docker-image:
    env:
      ALPINE_VERSION: 3.13
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Get Version
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
          tag: ${{ github.ref }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Dev Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: ohmyzsh
          labels: |
            github_repo: ${{ github.repository }}
            dockerhub_repo: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            INCLUDE_DOCS=true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.semver.outputs.non-prefixed }}

      - name: Build & Push Prod Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: ohmyzsh
          labels: |
            github_repo: ${{ github.repository }}
            dockerhub_repo: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            INCLUDE_DOCS=false
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:prod-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:prod-${{ steps.semver.outputs.non-prefixed }}

      - name: Build & Push Dev with glibc Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: glibc
          labels: |
            github_repo: ${{ github.repository }}
            dockerhub_repo: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            GLIBC_VERSION=2.33-r0
            INCLUDE_DOCS=true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:glibc-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:glibc-${{ steps.semver.outputs.non-prefixed }}

      - name: Build & Push PROD with glibc Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: glibc
          labels: |
            github_repo: ${{ github.repository }}
            dockerhub_repo: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            GLIBC_VERSION=2.33-r0
            INCLUDE_DOCS=false
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:prod-glibc-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:prod-glibc-${{ steps.semver.outputs.non-prefixed }}
   
  
