# Copyright (c) 2021 Jesse N. <jesse@keplerdev.com>
# This work is licensed under the terms of the MIT license. For a copy, see <https://opensource.org/licenses/MIT>.

name: "Publish Docker Image"

on:
  workflow_dispatch:
  release:
    types: [published]
    
env:
  LABELS: |
    "maintainer: Jesse N. <jesse@keplerdev.com>"
    "com.keplerdev.maintainer: Jesse N. <jesse@keplerdev.com>"
    "com.keplerdev.source-sha": ${{ github.sha }}
    "com.keplerdev.repository.github.url: https://github.com/${{ github.repository }}"
    "com.keplerdev.repository.dockerhub.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"

jobs:
  build-docker-image:
    runs-on: "ubuntu-latest"

    permissions:
      contents: read
      packages: write

    env:
      ALPINE_VERSION: latest
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Version
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
          tag: ${{ github.ref }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
          driver-opts: image=moby/buildkit:master
          use: true

      - name: Buildx Builder Create
        run: |
          docker buildx create --platform linux/amd64,linux/arm64/v8,linux/arm/v7

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: ohmyzsh
          labels: ${{ env.LABELS }}
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.semver.outputs.non-prefixed }}
            
      - name: Build & Push with glibc Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: glibc
          labels: ${{ env.LABELS }}
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            GLIBC_VERSION=2.33-r0
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest-glibc
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.semver.outputs.non-prefixed }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.semver.outputs.non-prefixed }}-glibc

      
