name: "Publish Docker Image"

on:
  workflow_dispatch:
  
    
jobs:
  build-docker-image:
    env:
      ALPINE_VERSION: 3.13
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Dev Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: ohmyzsh
          cache-to: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:cache, type=local, dest=/tmp/.buildx-cache
          cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:cache, type=local, dest=/tmp/.buildx-cache
          labels: |
            "com.keplerdev.alpine-zsh.maintainer: Jesse Nicholson <jesse@keplerdev.com>"
            "com.keplerdev.alpine-zsh.source-sha": ${{ github.sha }}
            "com.keplerdev.alpine-zsh.repository.github.url: https://github.com/${{ github.repository }}"
            "com.keplerdev.alpine-zsh.repository.dockerhub.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            INCLUDE_DOCS=true
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:next

      - name: Build & Push Dev with glibc Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: glibc
          cache-to: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:cache, type=local, dest=/tmp/.buildx-cache
          cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:cache, type=local, dest=/tmp/.buildx-cache
          labels: |
            "com.keplerdev.alpine-zsh.maintainer: Jesse Nicholson <jesse@keplerdev.com>"
            "com.keplerdev.alpine-zsh.source-sha": ${{ github.sha }}
            "com.keplerdev.alpine-zsh.repository.github.url: https://github.com/${{ github.repository }}"
            "com.keplerdev.alpine-zsh.repository.dockerhub.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            GLIBC_VERSION=2.33-r0
            INCLUDE_DOCS=true
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:glibc-next
  
