name: "Publish Docker Image"

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  build-docker-image:
    runs-on: "ubuntu-latest"

    permissions:
      contents: read
      packages: write

    env:
      ALPINE_VERSION: latest
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Get Version
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
          tag: ${{ github.ref }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
            install: true
            driver-opts: image=moby/buildkit:master
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Dev Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: ohmyzsh
          labels: |
            "maintainer: Jesse N. <jesse@keplerdev.com>"
            "com.keplerdev.alpine-zsh.maintainer: Jesse N. <jesse@keplerdev.com>"
            "com.keplerdev.alpine-zsh.source-sha": ${{ github.sha }}
            "com.keplerdev.alpine-zsh.repository.github.url: https://github.com/${{ github.repository }}"
            "com.keplerdev.alpine-zsh.repository.dockerhub.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            NO_DOCS=true
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.semver.outputs.non-prefixed }}

      - name: Build & Push Prod Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: ohmyzsh
          labels: |
            "maintainer: Jesse N. <jesse@keplerdev.com>"
            "com.keplerdev.alpine-zsh.maintainer: Jesse N. <jesse@keplerdev.com>"
            "com.keplerdev.alpine-zsh.source-sha": ${{ github.sha }}
            "com.keplerdev.alpine-zsh.repository.github.repository.url: https://github.com/${{ github.repository }}"
            "com.keplerdev.alpine-zsh.repository.dockerhub.repository.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            NO_DOCS=false
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:no-docs-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:no-docs-${{ steps.semver.outputs.non-prefixed }}

      - name: Build & Push Dev with glibc Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: glibc
          labels: |
            "maintainer: Jesse N. <jesse@keplerdev.com>"
            "com.keplerdev.alpine-zsh.maintainer: Jesse N. <jesse@keplerdev.com>"
            "com.keplerdev.alpine-zsh.source-sha": ${{ github.sha }}
            "com.keplerdev.alpine-zsh.repository.github.url: https://github.com/${{ github.repository }}"
            "com.keplerdev.alpine-zsh.repository.dockerhub.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            GLIBC_VERSION=2.33-r0
            NO_DOCS=true
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:glibc-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:glibc-${{ steps.semver.outputs.non-prefixed }}

      - name: Build & Push PROD with glibc Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: glibc
          labels: |
            "maintainer: Jesse N. <jesse@keplerdev.com>"
            "com.keplerdev.alpine-zsh.maintainer: Jesse N. <jesse@keplerdev.com>"
            "com.keplerdev.alpine-zsh.source-sha": ${{ github.sha }}
            "com.keplerdev.alpine-zsh.repository.github.url: https://github.com/${{ github.repository }}"
            "com.keplerdev.alpine-zsh.repository.dockerhub.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            GLIBC_VERSION=2.33-r0
            NO_DOCS=false
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:no-docs-glibc-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:no-docs-glibc-${{ steps.semver.outputs.non-prefixed }}
   