name: "Publish Docker Image"

on:
  workflow_dispatch:
  release:
    types: [published]
    

jobs:
    build-docker-image:
      runs-on: "ubuntu-latest"
  
      steps:
        - name: Checkout
          uses: actions/checkout@v2
      
        - name: Get Version
          id: semver
          uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
          with:
            tag: ${{ github.ref }}

        - name: Setup QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1

        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v1
        
        - name: Login to Dockerhub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          
#        - name: Login to GitHub Container Registry
#          uses: docker/login-action@v1
#          with:
#            username: ${{ github.repository_owner }}
#            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build & Push
          id: docker_build_step
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./amd64/Dockerfile
            labels: |
              github_repo: ${{ github.repository }}
              dockerhub_repo: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
            build-args: |
              ALPINE_VERSION=3.13.5
              OPENSSH_VERSION=8.1_p1-r0
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:glibc-latest
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:glibc-${{ steps.semver.outputs.non-prefixed }}
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.semver.outputs.non-prefixed }}
#              ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
#              ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest-glibc
#              ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest-${{ steps.semver.outputs.non-prefixed }}
#              ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.semver.outputs.non-prefixed }}
   
  
