# Copyright (c) 2021 Jesse N. <jesse@keplerdev.com>
# This work is licensed under the terms of the MIT license. For a copy, see <https://opensource.org/licenses/MIT>.

name: "Publish Docker Image"

on:
  push:
    tags:
      - "v*"
  # Run build once a week on Sunday to keep images up to date
  schedule:
    - cron: '0 0 0 0 0'

env:
  TARGET_PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7
  GHCR_URL: ghcr.io
  GHCR_LIBRARY: jessenich
  GHCR_REPO: alpine-zsh
  DOCKERHUB_LIBRARY: jessenich91
  DOCKERHUB_REPO: alpine-zsh
  LABELS: |
    maintainer=Jesse N. <jessenich@live.com>
    org.opencontainers.image.source=https://github.com/jessenich/docker-alpine-zsh

jobs:
  build-docker-image:
    name: Build Image - "${{ matrix.variant }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        alpine-version:
          - version: '3.13'
            latest: false
          - version: '3.14'
            latest: false
          - version: '3.15'
            latest: false
          - version: '3.16'
            latest: true
        user-mode: [ "root", "sudo" ]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
          driver-opts: image=moby/buildkit:master
          use: true

      - name: Cache Docker layers
        uses: actions/cache@v3.2.1
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.LABELS }}
          images: |
            ${{ env.DOCKERHUB_LIBRARY }}/${{ env.DOCKERHUB_REPO }}
            ghcr.io/${{ env.GHCR_LIBRARY }}/${{ env.GHCR_REPO }}
          tags: |
            type=raw,enable=${{ env.latest }},priority=100,value=latest
            type=raw,enable=${{ env.latest }},priority=100,value=${{ env.target }}
            type=raw,enable=true,priority=200,value=${{ env.target }}.${{ env.version }}
            type=semver,enable=${{ env.target == 'root' }},priority=300,pattern={{major}}.{{minor}}.{{patch}},suffix=-${{ env.version }}
            type=semver,enable=${{ env.target == 'root' }},priority=400,pattern={{major}}.{{minor}}.{{patch}},suffix=-root.${{ env.version }}
            type=semver,enable=${{ env.target == 'sudo' }},priority=300,pattern={{major}}.{{minor}}.{{patch}},suffix=-sudo.${{ env.version }}
          flavor: latest=false

      - name: Build & Push Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          labels: ${{ env.LABELS }}
          build-args: VARIANT=${{ matrix.user-mode }}.${{ matrix.variant }}
          platforms: ${{ env.PLATFORMS }}
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
